const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');const assert=require('node:assert/strict');
(async()=>{
const server=require('node:child_process').spawn('python',[require('node:path').join(__dirname,'browser_fixture.py')]);const port=String(await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('exit',code=>reject(new Error('server '+code)));})).trim();
const browser=await chromium.launch({executablePath:process.env.BIOFEEDBACK_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--use-gl=disabled','--no-zygote','--single-process','--in-process-gpu','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'],headless:true});
const page=await browser.newPage({viewport:{width:1180,height:850},acceptDownloads:true});let errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await page.goto('http://127.0.0.1:'+port);await page.evaluate(()=>{window.originalMedia=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);});await page.waitForSelector('[data-band-audio]');await page.waitForTimeout(500);
await page.locator('#compactPanels').click();assert(await page.locator('.signal-panel.view-mini').count()>20);
await page.locator('[data-band-audio="muse.band.alpha"]').click();assert(await page.evaluate(()=>signalState['muse.band.alpha'].audioOn));
await page.locator('#signalSearch').fill('heart rate');const before=await page.evaluate(()=>signalState['muse.band.alpha'].seq);await page.waitForTimeout(1200);assert(await page.evaluate(()=>signalState['muse.band.alpha'].seq)>before,'filtered audio polling must advance');
await page.locator('#signalSearch').fill('no such signal');await page.locator('#emptyAction').click();assert.equal(await page.locator('#signalSearch').inputValue(),'');
await page.locator('#muteAll').click();assert(await page.evaluate(()=>!Object.values(signalState).some(s=>s.audioOn)));
await page.locator('#recordBtn').click();await page.waitForFunction(()=>runtimeStatus.recording);await page.waitForTimeout(300);const download=await Promise.all([page.waitForEvent('download'),page.locator('#downloadRecording').click()]);assert(download[0].suggestedFilename().endsWith('.csv'));await page.locator('#recordBtn').click();await page.waitForFunction(()=>!runtimeStatus.recording);
await page.getByRole('tab',{name:'Device setup'}).click();
for(const id of ['lightstone','emwave','emwave2','emwave3','emwave4','muse']) {
 const toggle=page.locator('[data-device-toggle="'+id+'"]');await toggle.click();await page.waitForFunction(id=>catalog.devices.find(d=>d.id===id).running===false,id);await toggle.click();await page.waitForFunction(id=>catalog.devices.find(d=>d.id===id).running===true,id);
}
await page.route('**/api/muse_ports',route=>route.fulfill({json:{connections:[{kind:'bluetooth',device:'bt://one',bluetooth_name:'Muse One'},{kind:'bluetooth',device:'bt://two',bluetooth_name:'Muse Two'}],current:'bt://one'}}));await page.locator('#museScanPorts').click();await page.waitForFunction(()=>!museScanBusy);await page.locator('#musePortSelect').selectOption('bt://two');await page.locator('#themeToggle').click();await page.waitForTimeout(1200);assert.equal(await page.locator('#musePortSelect').inputValue(),'bt://two');await page.locator('#museSavePort').click();await page.waitForFunction(()=>runtimeStatus.muse_port==='bt://two');await page.unroute('**/api/muse_ports');
await page.locator('#oscHost').fill('localhost');await page.locator('#oscPort').fill('6000');await page.waitForTimeout(1300);assert.equal(await page.locator('#oscPort').inputValue(),'6000');await page.locator('#oscApply').click();await page.waitForFunction(()=>runtimeStatus.osc_port===6000);
await page.locator('.select-device').nth(2).click();assert((await page.locator('#selectedDevice').textContent()).includes('Unknown'));await page.locator('#scanBtn').click();await page.waitForFunction(()=>!diagnosticsBusy);assert((await page.locator('#selectedDevice').textContent()).includes('Unknown'));
await page.locator('#captureSeconds').selectOption('2');await page.locator('#captureDeviceBtn').click();await page.waitForTimeout(250);assert(await page.locator('#captureDeviceBtn').isDisabled());assert(await page.locator('#captureProgress').isVisible());await page.waitForFunction(()=>!diagnosticsBusy);assert((await page.locator('#diagOutput').textContent()).includes('Saved locally'));
await page.locator('#setupCamera').click();await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const e=new Error('denied');e.name='NotAllowedError';throw e;};});await page.locator('#cameraToggle').click();await page.waitForTimeout(100);assert((await page.locator('#error').textContent()).includes('Allow camera access'));assert.equal(await page.locator('#cameraToggle').textContent(),'Start camera');
// Cancel while getUserMedia is pending; the late stream must be stopped.
await page.evaluate(()=>{window.lateTracksStopped=0;navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{window.releaseCamera=()=>resolve({getTracks:()=>[{stop(){lateTracksStopped++}}],getVideoTracks:()=>[]});});});await page.locator('#cameraToggle').click();assert.equal(await page.locator('#cameraToggle').textContent(),'Cancel camera');await page.locator('#cameraToggle').click();await page.evaluate(()=>releaseCamera());await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>lateTracksStopped),1);assert(await page.evaluate(()=>cameraStream===null));
await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=originalMedia;});await page.locator('#cameraToggle').click();await page.waitForFunction(()=>cameraStream!==null&&!cameraStarting);await page.waitForTimeout(1500);assert(await page.evaluate(()=>cameraPendingSamples.length<31));await page.locator('#cameraMagnifyToggle').click();await page.locator('#cameraGuideX').fill('20');await page.locator('#cameraGuideY').fill('-20');assert(await page.evaluate(()=>cameraRectangles(320,240).every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=320&&r.y+r.h<=240)));await page.waitForTimeout(200);await page.locator('#cameraToggle').click();assert(await page.evaluate(()=>cameraStream===null&&document.getElementById('cameraVideo').srcObject===null));
// Recover cursors across a changed server session; mute on outage.
await page.evaluate(()=>{signalState['muse.band.alpha'].seq=999999;});await page.route('**/api/status',async route=>{const r=await route.fetch();const data=await r.json();data.session_id+=100;await route.fulfill({json:data});});await page.evaluate(()=>refreshAll());assert(await page.evaluate(()=>signalState['muse.band.alpha'].seq)<999999);await page.unroute('**/api/status');
await page.route('**/api/status',route=>route.abort());await page.evaluate(()=>refreshAll());assert(await page.locator('#connectionBanner').isVisible());await page.unroute('**/api/status');await page.evaluate(()=>refreshAll());assert(await page.locator('#connectionBanner').isHidden());

await page.evaluate(()=>switchTab('setup'));await page.locator('#quitApp').click();await page.waitForFunction(()=>document.getElementById('connectionBanner').hidden===false);
assert.deepEqual(errors,[]);console.log('Browser interactions passed: compact layout, filter/audio continuity, empty-state recovery, recording/download, OSC editing/apply, stable HID selection, capture progress, camera denial/cancellation, server restart/outage recovery.');
}finally{await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exit(1)});
